<?php

/**
 * @file
 * Remove site api key from system.site configuration.
 */

/**
 * Implements hook_uninstall().
 */
function expose_node_data_uninstall() {
  \Drupal::configFactory()->getEditable('system.site')->clear('siteapikey')->save();
}

/**
 * Implements hook_install().
 */
function expose_node_data_install() {
  \Drupal::configFactory()->getEditable('system.site')->set('siteapikey', 'No API Key yet')->save();
}
